package api

import "time"

type AutoGenerated struct {
	Data struct {
		Name                 string    `json:"name"`
		Account              string    `json:"account"`
		Skin                 string    `json:"skin"`
		Level                int       `json:"level"`
		Xp                   int       `json:"xp"`
		MaxXp                int       `json:"max_xp"`
		Gold                 int       `json:"gold"`
		Speed                int       `json:"speed"`
		MiningLevel          int       `json:"mining_level"`
		MiningXp             int       `json:"mining_xp"`
		MiningMaxXp          int       `json:"mining_max_xp"`
		WoodcuttingLevel     int       `json:"woodcutting_level"`
		WoodcuttingXp        int       `json:"woodcutting_xp"`
		WoodcuttingMaxXp     int       `json:"woodcutting_max_xp"`
		FishingLevel         int       `json:"fishing_level"`
		FishingXp            int       `json:"fishing_xp"`
		FishingMaxXp         int       `json:"fishing_max_xp"`
		WeaponcraftingLevel  int       `json:"weaponcrafting_level"`
		WeaponcraftingXp     int       `json:"weaponcrafting_xp"`
		WeaponcraftingMaxXp  int       `json:"weaponcrafting_max_xp"`
		GearcraftingLevel    int       `json:"gearcrafting_level"`
		GearcraftingXp       int       `json:"gearcrafting_xp"`
		GearcraftingMaxXp    int       `json:"gearcrafting_max_xp"`
		JewelrycraftingLevel int       `json:"jewelrycrafting_level"`
		JewelrycraftingXp    int       `json:"jewelrycrafting_xp"`
		JewelrycraftingMaxXp int       `json:"jewelrycrafting_max_xp"`
		CookingLevel         int       `json:"cooking_level"`
		CookingXp            int       `json:"cooking_xp"`
		CookingMaxXp         int       `json:"cooking_max_xp"`
		AlchemyLevel         int       `json:"alchemy_level"`
		AlchemyXp            int       `json:"alchemy_xp"`
		AlchemyMaxXp         int       `json:"alchemy_max_xp"`
		Hp                   int       `json:"hp"`
		MaxHp                int       `json:"max_hp"`
		Haste                int       `json:"haste"`
		CriticalStrike       int       `json:"critical_strike"`
		Stamina              int       `json:"stamina"`
		AttackFire           int       `json:"attack_fire"`
		AttackEarth          int       `json:"attack_earth"`
		AttackWater          int       `json:"attack_water"`
		AttackAir            int       `json:"attack_air"`
		DmgFire              int       `json:"dmg_fire"`
		DmgEarth             int       `json:"dmg_earth"`
		DmgWater             int       `json:"dmg_water"`
		DmgAir               int       `json:"dmg_air"`
		ResFire              int       `json:"res_fire"`
		ResEarth             int       `json:"res_earth"`
		ResWater             int       `json:"res_water"`
		ResAir               int       `json:"res_air"`
		X                    int       `json:"x"`
		Y                    int       `json:"y"`
		Cooldown             int       `json:"cooldown"`
		CooldownExpiration   time.Time `json:"cooldown_expiration"`
		WeaponSlot           string    `json:"weapon_slot"`
		ShieldSlot           string    `json:"shield_slot"`
		HelmetSlot           string    `json:"helmet_slot"`
		BodyArmorSlot        string    `json:"body_armor_slot"`
		LegArmorSlot         string    `json:"leg_armor_slot"`
		BootsSlot            string    `json:"boots_slot"`
		Ring1Slot            string    `json:"ring1_slot"`
		Ring2Slot            string    `json:"ring2_slot"`
		AmuletSlot           string    `json:"amulet_slot"`
		Artifact1Slot        string    `json:"artifact1_slot"`
		Artifact2Slot        string    `json:"artifact2_slot"`
		Artifact3Slot        string    `json:"artifact3_slot"`
		Utility1Slot         string    `json:"utility1_slot"`
		Utility1SlotQuantity int       `json:"utility1_slot_quantity"`
		Utility2Slot         string    `json:"utility2_slot"`
		Utility2SlotQuantity int       `json:"utility2_slot_quantity"`
		Task                 string    `json:"task"`
		TaskType             string    `json:"task_type"`
		TaskProgress         int       `json:"task_progress"`
		TaskTotal            int       `json:"task_total"`
		InventoryMaxItems    int       `json:"inventory_max_items"`
		Inventory            []struct {
			Slot     int    `json:"slot"`
			Code     string `json:"code"`
			Quantity int    `json:"quantity"`
		} `json:"inventory"`
	} `json:"data"`
}

type Character struct {
	Name    string `json:"name"`
	Account string `json:"account"`
	Skin    string `json:"skin"`

	Level int `json:"level"`
	XP    int `json:"xp"`
	MaxXP int `json:"max_xp"`
	Gold  int `json:"gold"`
	Speed int `json:"speed"`

	Hp    int `json:"hp"`
	MaxHP int `json:"max_hp"`
	Haste int `json:"haste"`

	X int `json:"x"` // character x coordinate
	Y int `json:"y"` // character y coordinate

	Cooldown           int       `json:"cooldown"`
	CooldownExpiration time.Time `json:"cooldown_expiration"` // string<date-time> per docs

	Armor       Armor
	TaskDetails TaskDetails
	FireStats   FireStats
	EarthStats  EarthStats
	WaterStats  WaterStats
	Skills      Skills

	InventoryMaxItems int             `json:"inventory_max_items"`
	Inventory         []InventorySlot `json:"inventory"`
}

type Skills struct {
	MiningLevel int `json:"mining_level"`
	MiningXP    int `json:"mining_xp"`
	MiningMaxXP int `json:"mining_max_xp"`

	WoodcuttingLevel int `json:"woodcutting_level"`
	WoodcuttingXP    int `json:"woodcutting_xp"`
	WoodcuttingMaxXP int `json:"woodcutting_max_xp"`

	FishingLevel int `json:"fishing_level"`
	FishingXP    int `json:"fising_xp"`
	FishingMaxXP int `json:"fishing_max_xp"`

	WeaponcraftingLevel int `json:"weaponcrafting_level"`
	WeaponcraftingXP    int `json:"weaponcrafting_xp"`
	WeaponcraftingMaxXP int `json:"weaponcrafting_max_xp"`

	GearcraftingLevel int `json:"gearcrafting_level"`
	GearcraftingXP    int `json:"gearcrafting_xp"`
	GearcraftingMaxXP int `json:"gearcrafting_max_xp"`

	JewelrycraftingLevel int `json:"jewelrycrafting_level"`
	JewelrycraftingXP    int `json:"jewelrycrafting_xp"`
	JewelrycraftingMaxXP int `json:"jewelrycrafting_max_xp"`

	CookingLevel int `json:"cooking_level"`
	CookingXP    int `json:"cooking_xp"`
	CookingMaxXP int `json:"cooking_max_xp"`

	AlchemyLevel int `json:"alchemy_level"`
	AlchemyXP    int `json:"alchemy_xp"`
	AlchemyMaxXP int `json:"alchemy_max_xp"`
}

type FireStats struct {
	AttackFire int `json:"attack_fire"`
	DmgFire    int `json:"dmg_fire"`
	ResFire    int `json:"res_fire"`
}

type EarthStats struct {
	AttackEarth int `json:"attack_earth"`
	DmgEarth    int `json:"dmg_earth"`
	ResEarth    int `json:"res_earth"`
}

type WaterStats struct {
	AttackWater int `json:"attack_water"`
	DmgWater    int `json:"dmg_water"`
	ResWater    int `json:"res_water"`
}

type AirStats struct {
	AttackAir int `json:"attack_air"`
	DmgAir    int `json:"dmg_air"`
	ResAir    int `json:"res_air"`
}

type Armor struct {
	WeaponSlot           string `json:"weapon_slot"`
	ShieldSlot           string `json:"shield_slot"`
	HelmetSlot           string `json:"helmet_slot"`
	BodyArmorSlot        string `json:"body_armor_slot"`
	LegArmorSlot         string `json:"leg_armor_slot"`
	BootsSlot            string `json:"boots_slot"`
	Ring1Slot            string `json:"ring1_slot"`
	Ring2Slot            string `json:"ring2_slot"`
	AmuletSlot           string `json:"amulet_slot"`
	Artifact1Slot        string `json:"artifact1_slot"`
	Artifact2Slot        string `json:"artifact2_slot"`
	Artifact3Slot        string `json:"artifact3_slot"`
	Utility1Slot         string `json:"utility1_slot"`
	Utility1SlotQuantity int    `json:"utility1_slot_quantity"`
	Utility2Slot         string `json:"utility2_slot"`
	Utility2SlotQuantity int    `json:"utility2_slot_quantity"`
}

type TaskDetails struct {
	Task         string `json:"task"`
	TaskType     string `json:"task_type"`
	TaskProgress int    `json:"task_progress"`
	TaskTotal    int    `json:"task_total"`
}

type InventorySlot struct {
	Slot     int    `json:"slot"`
	Code     string `json:"code"`
	Quantity int    `json:"quantity"`
}
